### ISSUE TITLE
Ideal and question

### ISSUE THREAD

**Issue by rayiik** [tjameswhite/honeypot-form#1]
Hello, so first off very nice. I don't see a license with this so my question is may i use this with attribution and modification (though would be pulling the git-hub sections). Also just an ideal or two that would be really nice to implement. A reverse time out, where if the form is filled out too fast. Limiting the number repeat times within a window in which forms may be submitted from a specific ip address.

**Comment by tjameswhite** [comment]
@rayiik -- I'll add an attribution, but yes you may use with attribution. Thank you for asking. I haven't touched it in a long time so any additions you have would be welcomed.

**Comment by rayiik** [comment]
hey thanks a lot, my client seems to be back and forth on what he's looking for so may or may not need it but im not 100% sure his problem is bots on his form testing that one out first and ill defiantly do a pull request if i end up implementing changes. And if not for his site defiantly for mine when i find some free time and can get to it :)
